services:
  # Spring Boot web service
  - type: web
    name: prime-app-backend
    env: docker
    plan: standard
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    healthCheckPath: /api/v1/actuator/health
    repo: https://github.com/kai-lucky72/prime_app.git
    branch: main
    numInstances: 1
    healthCheckTimeout: 5
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: prime-app-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: prime-app-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: prime-app-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: prime-app-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: prime-app-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: FILE_UPLOAD_DIR
        value: /var/data/uploads

# MySQL database
databases:
  - name: prime-app-db
    plan: standard
    type: mysql
    version: '8'
    postCreate:
      sql: |
        CREATE DATABASE IF NOT EXISTS prime_app_db;
        CREATE USER IF NOT EXISTS 'prime_app'@'%' IDENTIFIED BY '${DB_PASSWORD}';
        GRANT ALL PRIVILEGES ON prime_app_db.* TO 'prime_app'@'%';
        FLUSH PRIVILEGES;
